### PR TITLE
add Riot and Domrender to the 'Extreme Benchmark'

### PR DESCRIPTION
**Pull request by drewlesueur**

### CODE REVIEW

**Comment by pakastin** [comment]
Thanks! I'll check this out as soon as possible..

**Comment by pakastin** [comment]
Are you using DOM reordering with Domrender?

**Comment by drewlesueur** [comment]
No, I am not using DOM reordering. If this benchmark is supposed to only test DOM reordering, I am fine removing the pull request. :)

**Comment by pakastin** [comment]
Yeah, it is.. ;) Of course replacing textContent will be faster.. You can do that with FRZR by removing the key attribute (with just ```view.reset(data)```)

**Comment by pakastin** [comment]
I think Riot also doesn't use reordering by default no more..

**Comment by drewlesueur** [comment]
Got it. Thank you.

**Comment by pakastin** [comment]
Thanks anyway! If you could modify them to use reordering, would be great to see the performance! Riot is actually using almost similar reordering, since I'm one of the contributors..

**Comment by drewlesueur** [comment]
Cool. I will consider adding reordering. Thank you for the feedback.

**Pull request closed without merging**
